all:
	gcc -Wall heavens_door.c -o heavens_door
	gcc -Wall r00t.c -o r00t
	gcc -Wall knock_on_heaven.c -o knock_on_heaven
	cp  heavens_door knock_on_heaven r00t ../bin
clean:
	rm -rf heavens_door knock_on_heaven r00t
